In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("/dbfs/FileStore/tables/property_data-11e95.csv")

In [3]:
print(df.head())

In [4]:
print(df["ST_NUM"])
print("\n")
print(df["ST_NUM"].isnull())

In [5]:
missing_values = ["n/a", "na", "--"]

In [6]:
df = pd.read_csv("/dbfs/FileStore/tables/property_data-11e95.csv", na_values = missing_values)

In [7]:
print(df.head())

In [8]:
print(df["NUM_BEDROOMS"])
print(df["NUM_BEDROOMS"].isnull())

In [9]:
print(df["OWN_OCCUPIED"])
print(df["OWN_OCCUPIED"].isnull())

In [10]:
counter = 0
for row in df["OWN_OCCUPIED"]:
    try:
        int(row)
        df.loc[counter, "OWN_OCCUPIED"]=np.nan
    except ValueError:
        pass
    counter+=1

In [11]:
print(df.isnull().sum())

In [12]:
print (df.isnull().values.any())

In [13]:
print(df.isnull().sum().sum())

In [14]:
df['ST_NUM'].fillna(125, inplace=True)

In [15]:
df.loc[2,'ST_NUM'] = 125

In [16]:
median = df['NUM_BEDROOMS'].median()
df['NUM_BEDROOMS'].fillna(median, inplace=True)

In [17]:
print(df.head())

In [18]:
print(df.isnull().sum().sum())